## GET ALL ALBUM
GET http://localhost:5050/api/album HTTP/1.1

### GET ONE ALBUM
GET http://localhost:5050/api/album/421d451a-aaac-4192-8ec3-27be99009237 HTTP/1.1

### POST ALBUM
POST http://localhost:5050/api/album HTTP/1.1
Content-Type: application/json

{
    "name": "St", 
    "note": "Second album for Harbour Rebles",
    "folder": "Toulouse",
    "artist": "Harbour Rebels",
    "style": "Street Punk"
}
    

### PUT ALBUM
PUT http://localhost:5050/api/album/c71db1c3-5d7e-4931-9af1-62811ab47160 HTTP/1.1
Content-Type: application/json

{
    "name": "Messed Up",
    "country" : "Bielorussie",
    "town": "Grobno"
}

### DELETE ALBUM
DELETE  http://localhost:5050/api/album/b353bd82-31a1-4649-b7fb-e76f6d2165ae HTTP/1.1
