## GET ALL ARTISTS
GET http://localhost:5050/api/artist HTTP/1.1

### GET ONE ARTIST
GET http://localhost:5050/api/artist/421d451a-aaac-4192-8ec3-27be99009237 HTTP/1.1

### POST ARTIST
POST http://localhost:5050/api/artist HTTP/1.1
Content-Type: application/json

{
  "name": "Krav Boca",
  "CityId": "7ccc38cc-f348-433b-a2b9-0d4f51f666e5",
  "CountryId": "cf272243-9e43-47c6-a846-4609b2d83790"

}
    

### PUT ARTIST
PUT http://localhost:5050/api/artist/ff3c5e9a-b156-4e49-af54-a4a90e4ec4f8 HTTP/1.1
Content-Type: application/json

{
  "name": "Brixton Cats"  
}

### DELETE ARTIST
DELETE  http://localhost:5050/api/artist/ef850433-f91f-4f03-9329-ef9cf24cbaf2 HTTP/1.1
