## GET ALL LOCATION
GET http://localhost:5050/api/location HTTP/1.1

### GET ONE LOCATION
GET http://localhost:5050/api/location/421d451a-aaac-4192-8ec3-27be99009237 HTTP/1.1

### POST LOCATION
POST http://localhost:5050/api/location HTTP/1.1
Content-Type: application/json

{
    "name": "Donostia"
}

### PUT LOCATION
PUT http://localhost:5050/api/location/141a0ffd-53db-4319-adb9-2679c9ec97d9 HTTP/1.1
Content-Type: application/json

{
    "name": "Euskal Herria"
}

### DELETE ARTILOCATIONST
DELETE  http://localhost:5050/api/location/b353bd82-31a1-4649-b7fb-e76f6d2165ae HTTP/1.1