## GET ALL PRICE
GET http://localhost:5050/api/price HTTP/1.1

### GET ONE PRICE
GET http://localhost:5050/api/price/1c0be236-5379-4e11-b0c7-fb164ae64e9d HTTP/1.1

### POST PRICE
POST http://localhost:5050/api/price HTTP/1.1
Content-Type: application/json

{
    "price": 900
}

### PUT PRICE
PUT http://localhost:5050/api/price/2b1831b3-eaee-4e37-8ad5-f907d246badb HTTP/1.1
Content-Type: application/json

{
    "name": "Hardcore"
}

### DELETE PRICE
DELETE  http://localhost:5050/api/price/5958ba5f-f400-4a49-a77a-74356de4457e HTTP/1.1