## GET ALL ALBUM
GET http://localhost:5050/api/album HTTP/1.1

### GET ONE ALBUM
GET http://localhost:5050/api/album/c56a446c-089e-4ea3-8425-c25d8a4b9eab HTTP/1.1

### POST ALBUM
POST http://localhost:5050/api/album HTTP/1.1
Content-Type: application/json

{
    "name": "City Hacker", 
    "note": "Second album for Harbour Rebels",
    "folder": "http://ok.com",
    "ArtistId": "0bc032a9-0945-4125-9f7c-4e8c61bb4f57",
    "StyleId": "448ff516-6015-41ac-a257-76d4744c50b5",
    "tracklist": [
        {"name":"Intro", "track": 1 },
        {"name":"Souterrain feat Chata Flores", "track":2 },
        {"name":"Kravmikaz", "track":3 },
        {"name":"Camtar", "track":4 },
        {"name":"Crust feat My Own Voice, Matrak Attakk", "track": 5},
        {"name":"GasMask feat Speira", "track":6 },
        {"name":"Poison feat Zafina","track": 7},
        {"name":"Carte Postale feat Al Nasser", "track":8 },
        {"name":"City Hackers feat Aeon", "track":9 }
    ],
    "labels": [
        {"name":"Rumagna Sgroza" },
        {"name":"Mass Productions" },
        {"name":"Fire & Flames", "friend": true },
        {"name":"General Strike" },
        {"name":"Guerilla Vinyl" },
        {"name":"Blackout Brigade" },
        {"name":"Brigada Caoz" },
        {"name":"Maloka Collective" },
        {"name":"KeponTeam" },
        {"name":"Up The Punx" },
        {"name":"Subversivez ways" },
        {"name":"Punti Scena Records" }
    ]    
}

### PUT ALBUM
PUT http://localhost:5050/api/album/174b7094-bf14-40f0-a7b7-30fc3541e649 HTTP/1.1
Content-Type: application/json

{
    "name": "Messed Up",
    "country" : "Bielorussie",
    "town": "Grobno"
}

### DELETE ALBUM
DELETE  http://localhost:5050/api/album/ HTTP/1.1
