## GET ALL ALBUM
GET http://localhost:5050/api/albums HTTP/1.1

### GET ONE ALBUM
GET http://localhost:5050/api/album/c56a446c-089e-4ea3-8425-c25d8a4b9eab HTTP/1.1

### POST ALBUM
POST http://localhost:5050/api/albums HTTP/1.1
Content-Type: application/json

{
    "name": "City Hacker", 
    "note": "Second album for Harbour Rebels",
    "folder": "https://www.coreandco.fr/upload/pics/albums2/big/krav-boca-city-hackers-7844.jpg",
    "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736",
    "StyleId": "ed0fab94-d6d0-4756-bf1a-ba116bdeef54",
    "tracklist": [
        {"name":"Intro", "track": 1, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"}, 
        {"name":"Souterrain feat Chata Flores", "track": 2, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"Kravmikaz", "track": 3, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"Camtar", "track": 4, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"Crust feat My Own Voice, Matrak Attakk", "track": 5, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"GasMask feat Speira", "track": 6, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"Poison feat Zafina", "track": 7, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"Carte Postale feat Al Nasser", "track": 8, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736"},
        {"name":"City Hackers feat Aeon", "track": 9, "ArtistId": "d1cab072-2e64-46b0-9318-ffdbef497736" }
    ],
    "labels": [
        {"name":"Rumagna Sgroza" },
        {"name":"Mass Productions" },
        {"name":"Fire & Flames", "friend": true },
        {"name":"General Strike" },
        {"name":"Guerilla Vinyl" },
        {"name":"Blackout Brigade" },
        {"name":"Brigada Caoz" },
        {"name":"Maloka Collective" },
        {"name":"KeponTeam" },
        {"name":"Up The Punx" },
        {"name":"Subversivez ways" },
        {"name":"Punti Scena Records" }
    ],
    "videos": [
        {"youtube_url": "https://www.youtube.com/watch?v=jFT_vJyOAfQ"},
        {"youtube_url": "https://www.youtube.com/watch?v=SImF_Hq5h84"},
        {"youtube_url": "https://www.youtube.com/watch?v=jeO9KDHNjLA"}
    ]
}

### PUT ALBUM
PUT http://localhost:5050/api/album/174b7094-bf14-40f0-a7b7-30fc3541e649 HTTP/1.1
Content-Type: application/json

{
    "name": "Messed Up",
    "country" : "Bielorussie",
    "town": "Grobno"
}

### DELETE ALBUM
DELETE  http://localhost:5050/api/albums/ HTTP/1.1
