## GET ALL ALBUM
GET http://localhost:5050/api/album HTTP/1.1
Access-Control-Allow-Origin: *

### GET ONE ALBUM
GET http://localhost:5050/api/album/421d451a-aaac-4192-8ec3-27be99009237 HTTP/1.1

### POST ALBUM
POST http://localhost:5050/api/album HTTP/1.1
Access-Control-Allow-Origin: *
Content-Type: application/json

{
    "name": "City Hacker", 
    "note": "Second album for Harbour Rebels",
    "folder": "http://ok.com",
    "ArtistId": "47a47914-5eea-4604-8b79-69d704c8c09c",
    "StyleId": "86efd39b-2aee-448b-8ff2-a48613f85a3c",
    "tracklist": [
        {"name":"Intro", "track":1 },
        {"name":"Souterrain feat Chata Flores", "track":2 },
        {"name":"Kravmikaz", "track":3 },
        {"name":"Camtar", "track":4 },
        {"name":"Crust feat My Own Voice, Matrak Attakk", "track": 5},
        {"name":"GasMask feat Speira", "track":6 },
        {"name":"Poison feat Zafina","track": 7},
        {"name":"Carte Postale feat Al Nasser", "track":8 },
        {"name":"City Hackers feat Aeon", "track":9 }
    ],
    "labels": [
        {"name":"Rumagna Sgroza" },
        {"name":"Mass Productions" },
        {"name":"Fire & Flames", "friend": true },
        {"name":"General Strike" },
        {"name":"Guerilla Vinyl" },
        {"name":"Blackout Brigade" },
        {"name":"Brigada Caoz" },
        {"name":"Maloka Collective" },
        {"name":"KeponTeam" },
        {"name":"Up The Punx" },
        {"name":"Subversivez ways" },
        {"name":"Punti Scena Records" }
    ]    
}

### PUT ALBUM
PUT http://localhost:5050/api/album/174b7094-bf14-40f0-a7b7-30fc3541e649 HTTP/1.1
Content-Type: application/json

{
    "name": "Messed Up",
    "country" : "Bielorussie",
    "town": "Grobno"
}

### DELETE ALBUM
DELETE  http://localhost:5050/api/album/ HTTP/1.1
