### ALL ARTICLE
GET http://localhost:5050/api/articles HTTP/1.1

###ONE ARTICLE
GET http://localhost:5050/api/articles/tape HTTP/1.1

### POST ARTICLE
POST http://localhost:5050/api/articles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heGlsb3VkIiwiZW1haWwiOiJrYWxlLmJvcnJva2EucmVjb3Jkc0Bwcm90b25taWwuY29tIiwidXNlcnR5cGUiOiJBRE1JTiIsImlhdCI6MTYyNTM4ODY4OCwiZXhwIjoxNjI1Mzk5NDg4fQ.q2o1mlBb2jpsRcwBc_Em5hTRuDLli8kNverGxFyNdLQ

{
    "AlbumId": "89d3ff35-1e53-4ede-88eb-0fd2259e95bf",
    "FormatId": "a09dfa6f-9ad8-4558-8457-4f868450e753",
    "PriceId": "797deab7-4caf-448a-abb4-043acccd0c91",
    "QuantityId": "36502a8d-d856-436b-9614-fc6ee166c522"
}
