## GET ALL ARTISTS
GET http://localhost:5050/api/artist HTTP/1.1

### GET ONE ARTIST
GET http://localhost:5050/api/artist/421d451a-aaac-4192-8ec3-27be99009237 HTTP/1.1

### POST ARTIST
POST http://localhost:5050/api/artist HTTP/1.1
Content-Type: application/json

{
  "name": "Krav Boca",
  "CityId": "703d5fa0-a991-422d-87ac-08c6c3515253",
  "CountryId": "8e49df12-6d22-4ab9-bf79-64583a60f682"

}
    

### PUT ARTIST
PUT http://localhost:5050/api/artist/e9c34d96-d4f3-4019-bd4f-596343cec444 HTTP/1.1
Content-Type: application/json

{
  "name": "Krav Boca"  
}

### DELETE ARTIST
DELETE  http://localhost:5050/api/artist/ef850433-f91f-4f03-9329-ef9cf24cbaf2 HTTP/1.1
