### ALL ARTICLE
GET http://localhost:5050/api/articles HTTP/1.1

###ONE ARTICLE
GET http://localhost:5050/api/articles/tape HTTP/1.1

### POST ARTICLE
POST http://localhost:5050/api/articles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heGlsb3VkIiwiZW1haWwiOiJrYWxlLmJvcnJva2EucmVjb3Jkc0Bwcm90b25tYWlsLmNvbSIsInVzZXJ0eXBlIjoiQURNSU4iLCJpYXQiOjE2NDMyODI5NTMsImV4cCI6MTY0MzM2OTM1M30.ZwjpYuVQB1fUuZYywqKI4Ir97Tc1lyqNWOJ9vm6au0g

{
    "name": "Krav Boca - Barrikade",
    "quantity": 15,
    "price": 1000,
    "AlbumId": "78a186af-7773-4ab4-b85b-a082a1681134",
    "FormatId": "80092ba3-b6d8-416f-8d78-ad66f5e7186d"
}
