### SIGNUP USER
POST http://localhost:5050/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "maxiloud",
    "password": "maxiloud.161",
    "email": "kale.borroka.records@protonmil.com",
    "usertype": "ADMIN"
}

### LOGIN USER
POST http://localhost:5050/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "maxiloud",
    "password": "maxiloud.161"   
}
