## GET ALL CITIES
GET http://localhost:5050/api/cities HTTP/1.1

### GET ONE CITY
GET http://localhost:5050/api/cities/b6014978-0f99-4a42-a3b2-dd94304666a5 HTTP/1.1

### POST CITY
POST http://localhost:5050/api/cities HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heGlsb3VkIiwiZW1haWwiOiJrYWxlLmJvcnJva2EucmVjb3Jkc0Bwcm90b25tYWlsLmNvbSIsInVzZXJ0eXBlIjoiQURNSU4iLCJpYXQiOjE2MzY4OTc1MTgsImV4cCI6MTYzNjkwODMxOH0.tDLdHzJLxo2dG-s1KfQB0NT55TBNgSop0PV8KYyMwU0

{
  "city": "Toulouse"
}


### PUT CITY
PUT http://localhost:5050/api/cities/59541733-8c3f-4c55-bcc3-ffa54f0f8627 HTTP/1.1
Content-Type: application/json

{
  "city": "PARIS"
}

### DELETE CITY
DELETE  http://localhost:5050/api/cities/59541733-8c3f-4c55-bcc3-ffa54f0f8627 HTTP/1.1
