## GET ALL CITIES
GET http://localhost:5050/api/city HTTP/1.1

### GET ONE CITY
GET http://localhost:5050/api/city/3e45291a-e9f1-4f60-a0ac-1f8c2263ef24 HTTP/1.1

### POST CITY
POST http://localhost:5050/api/city HTTP/1.1
Content-Type: application/json

{  
  "city": "Toulouse"  
}
    

### PUT CITY
PUT http://localhost:5050/api/city/3e45291a-e9f1-4f60-a0ac-1f8c2263ef24 HTTP/1.1
Content-Type: application/json

{  
  "city": "LouseTou"  
}

### DELETE CITY
DELETE  http://localhost:5050/api/city/3e45291a-e9f1-4f60-a0ac-1f8c2263ef24 HTTP/1.1