## GET ALL PRICE
GET http://localhost:5050/api/prices HTTP/1.1

### GET ONE PRICE
GET http://localhost:5050/api/prices/352cc662-c18b-4f0e-b68a-5add2e9619db HTTP/1.1

### POST PRICE
POST http://localhost:5050/api/prices HTTP/1.1
Content-Type: application/json

{
    "price": 1000
}

### PUT PRICE
PUT http://localhost:5050/api/prices/352cc662-c18b-4f0e-b68a-5add2e9619db HTTP/1.1
Content-Type: application/json

{
    "price": 1500
}

### DELETE PRICE
DELETE  http://localhost:5050/api/prices/352cc662-c18b-4f0e-b68a-5add2e9619db HTTP/1.1