### POST SONG INTO TRACKLIST

POST http://localhost:5050/api/tracklist http/1.1
Content-Type: application/json

{
  "track":"1",
  "trackilist": [
    {"name":"Intro", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"Souterrain feat Chata Flores", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"Kravmikaz", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"Camtar", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"Crust feat My Own Voice, Matrak Attakk", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"GasMask feat Speira", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"Poison feat Zafina", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"Carte Postale feat Al Nasser", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"},
    {"name":"City Hackers feat Aeon", "ArtistId": "75880562-3aa9-4aad-a116-c3562ad20ee3"}
  ]
  }