import bfm from "./img/bfm.jpg";
import brixtoncats from "./img/brixtoncats.jpg";
import grabuge from "./img/grabuge.jpg";
import keltoi from "./img/keltoi.jpg";
import kronstadt from "./img/kronstadt.jpg";
import mdb from "./img/mdb.jpg";
import sharpcut from "./img/sharpcut.jpg";
import traitre from "./img/traitre.jpg";
import urbanvietcong from "./img/urbanvietcong.jpg";
import va from "./img/va.jpg";

const article = [
    {
        id: 350705,
        artiste: "Brigada Flores Magon",
        name: "ST",
        image: `${bfm}`,
        price: "11€",
        format: "LP",
    },
    {
        id: 6763714,
        artiste: "Brixton Cats",
        name: "Quartier Maudit",
        image: `${brixtoncats}`,
        price: "10€",
        format: "LP",
    },
    {
        id: 12202674,
        artiste: "Grabuge",
        name: "Perdu D'avance",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 9477937,
        artiste: "Keltoi",
        name: "Son da rua",
        image: "./img/bfm.jpg",
        price: "13€",
        format: "LP",
    },
    {
        id: 12539863,
        artiste: "Kronstadt",
        name: "ST",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 11415341,
        artiste: "Moscow Death Brigade",
        name: "Boltcutter",
        image: "./img/bfm.jpg",
        price: "13€",
        format: "LP",
    },
    {
        id: 13312057,
        artiste: "SharpxCut",
        name: "Trouble from the street",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 13236389,
        artiste: "Traitre",
        name: "discographie",
        image: "./img/bfm.jpg",
        price: "13€",
        format: "LP",
    },
    {
        id: 13008350,
        artiste: "Urban Vietcong",
        name: "Storai tra bottiglie e ciminiere",
        image: "./img/bfm.jpg",
        price: "13€",
        format: "LP",
    },
    {
        id: 10364210,
        artiste: "Various Artist",
        name: "Oi! in Head, Punk in heart",
        image: "./img/bfm.jpg",
        price: "11€",
        format: "LP",
    },
    {
        id: 9207145,
        artiste: "Death or Glory",
        name: "Fearless",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 14994437,
        artiste: "Death or Glory",
        name: "Can't stop Me",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 4988617,
        artiste: "The Midnight Rovers",
        name: "Rockin' Class",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 4106520,
        artiste: "Skuds and Panic People",
        name: "Lachez les bombes",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 10464304,
        artiste: "Knock Out",
        name: "Tiempo muertos, Ritmos inmortales",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 10595877,
        artiste: "Cartouche",
        name: "A venir",
        image: "./img/bfm.jpg",
        price: "11€",
        format: "LP",
    },
    {
        id: 3356565,
        artiste: "65 Mines Street",
        name: "ST",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 3907774,
        artiste: "Opcio k-95",
        name: "Reneix",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 1316250,
        artiste: "210",
        name: "Пыль В Глаза ",
        image: "./img/bfm.jpg",
        price: "12€",
        format: "LP",
    },
    {
        id: 3018198,
        artiste: "Jeunesse Apatride",
        name: " Black Block 'N' Roll / La Victoire Sommeille ",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 14421523,
        artiste: "Messed Up",
        name: " Всё во что ты веришь / Everything You Believe In ",
        image: "./img/bfm.jpg",
        price: "13€",
        format: "LP",
    },
    {
        id: 12019515,
        artiste: "Enraged Minority",
        name: " A world to win ",
        image: "./img/bfm.jpg",
        price: "12€",
        format: "LP",
    },
    {
        id: 8299937,
        artiste: "Bull Brigade",
        name: " Vita Liberta ",
        image: "./img/bfm.jpg",
        price: "12€",
        format: "LP",
    },
    {
        id: 9230162,
        artiste: "Stumbling Pins",
        name: " Common Angst ",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "LP",
    },
    {
        id: 12589838,
        artiste: "Bull Brigade, Non Servium",
        name: " Common Angst ",
        image: "./img/bfm.jpg",
        price: "10€",
        format: "10",
    },
];

export default article;
