import skin2 from "./"

const matosIpeh = [
    {
        id:"" ,
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"" ,
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"",
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"" ,
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"",
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"" ,
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"" ,
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"" ,
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id: "",
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
    {
        id:"",
        artiste: "Knock Out",
        name: "Rock'n'roll Skinhead",
        image: `${skin2}`,
        price: "10€",
        format: "EP",
        quantity: "1",
    },
];

export default matosIpeh;
